os: linux
arch: amd64
dist: xenial
vm:
  size: large
rvm: 2.6.3
jobs:
  include:
    - stage: "sleep"
      script: sleep 5
notifications:
  email:
    - shairyarbaig@gmail.com
    - shairyarbaig@gmail.com
