language: python
install: skip

jobs:
  include:
    - dist: xenial
      os: freebsd
      arch: ppc64le
      vm:
        size: medium
      script:
      - echo "Threads/core $(nproc --all)"
      - free -g
