jobs:
  include:
    - os: windows
      language: c
      arch: amd64
      vm:
        size: medium
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
    - os: windows
      language: c
      arch: amd64
      vm:
        size: large
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
    - os: windows
      language: c
      arch: amd64
      vm:
        size: x-large
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
    - os: windows
      language: c
      arch: amd64
      vm:
        size: 2x-large
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
    - os: freebsd
      language: c
      arch: amd64
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
    - os: linux
      language: c
      dist: xenial
      arch: amd64
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
    - os: linux
      language: c
      dist: bionic
      arch: amd64
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
    - os: linux
      language: c
      dist: focal
      arch: amd64
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
