language: python
install: skip

jobs:
  include:
    - dist: focal
      os: linux
      vm:
        size: medium
      script:
      - echo "Threads/core $(nproc --all)"
      - free -g
    - dist: focal
      os: linux
      vm:
        size: large
      script:
      - echo "Threads/core $(nproc --all)"
      - free -g

